### ISSUE TITLE
i have an idea for notepad++,can you help me

### ISSUE THREAD

**Issue by denglaxiong** [ffes/npptags#7]
i have an idea for notepad++,can you help me, this is my code->https://github.com/denglaxiong/NppRegexReplace.git

**Comment by ffes** [comment]
Really haven't got a clue why this issue is opened. AFAICS it has nothing to do with my plugin.

**Comment by denglaxiong** [comment]
what?

**Comment by ffes** [comment]
I considered not even to reply, but do so anyway...

You opened an issue on my project that feels a lot like spam although it might not be. Not sure though. It is just a link without any real context to a repository that is purely Chinese, a language I don't understand. 

I can only **guess** you created some plugin for notepad++ that had something to do with regexs.

You give no information why this repository is related to my plugin (my plugin had nothing to do with regexs) or why I should even consider spending my precious time on it. Even after I closed the issue you still don't give any additional information just a rude "what?".

The questions remain the same.

How is this related to my plugin?
Why should I consider spending time on it?

**Comment by denglaxiong** [comment]
I want your help for my plugin with regex ,i am java programmer



***@***.***
 
From: Frank Fesevur
Date: 2022-03-23 19:57
To: ffes/npptags
CC: denglaxiong; Author
Subject: Re: [ffes/npptags] i have an idea for notepad++,can you help me (Issue #7)
I considered not even to reply, but do so anyway...
You opened an issue on my project that feels a lot like spam although it might not be. Not sure though. It is just a link without any real context to a repository that is purely Chinese, a language I don't understand.
I can only guess you created some plugin for notepad++ that had something to do with regexs.
You give no information why this repository is related to my plugin (my plugin had nothing to do with regexs) or why I should even consider spending my precious time on it. Even after I closed the issue you still don't give any additional information just a rude "what?".
The questions remain the same.
How is this related to my plugin?
Why should I consider spending time on it?
